### ISSUE TITLE
Error L6200E

### ISSUE THREAD

**Issue by mfeist** [sonnle/srdesign#7]
I get this error now when I compile the code in the different files.  When I looked up that error, they corrected in __inline.  Not sure where that is at. I will look into that tomorrow.

**Comment by mfeist** [comment]
Figured it out. I had to take out #include "Control.c" and replace with #include "LPC17xx.h"  Should be ready for testing on Monday.

**Comment by sonnle** [comment]
Yeah, I had to do this too on my Eclipse to get it to compile there, with the files separated.
